### ISSUE TITLE
suport remove package command

### ISSUE THREAD

**Issue by yazaldefilimone** [yazaldefilimone/nu.rs#2]
Add support for removing packages. The `remove` command should:

- Remove specified packages from dependencies or dev-dependencies.
- Update the `lockfile` and `package.json`.
- Handle orphaned dependencies properly.

### Tasks

- [ ] Implement logic for removing packages.
- [ ] Update `package.json` and `lockfile`.
- [ ] Handle orphaned dependencies.
