### ISSUE TITLE
support lock files for npm, pnpm, and bun

### ISSUE THREAD

**Issue by yazaldefilimone** [yazaldefilimone/nu.rs#3]
expand the package manager to support lock files from different managers, including npm, pnpm, and bun. This includes reading and writing these formats.

### Tasks

- [ ] support `npm` `package-lock.json`.
- [ ] support `pnpm` `pnpm-lock.yaml`.
- [ ] support `bun` `bun.lockb`.
