### ISSUE TITLE
other Commands (e.g., update, upgrade, list)

### ISSUE THREAD

**Issue by yazaldefilimone** [yazaldefilimone/nu.rs#4]
add support for other essential commands such as `update`, `upgrade`, and `list`.

### Tasks

- [ ] Implement `update` command.
- [ ] Implement `upgrade` command.
- [ ] Implement `list` command.
